# Generated by Django 6.0.6 on 2026-06-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="home",
            new_name="Post",
        ),
    ]
